# Generated by Django 3.2.12 on 2024-11-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('debut_movie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FilmedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('studio_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.director')),
                ('studios', models.ManyToManyField(through='trivia_game.FilmedBy', to='trivia_game.Studio')),
            ],
        ),
        migrations.CreateModel(
            name='MediumTrivia',
            fields=[
                ('trivia_id', models.AutoField(primary_key=True, serialize=False)),
                ('trivia_fact', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardTrivia',
            fields=[
                ('trivia_id', models.AutoField(primary_key=True, serialize=False)),
                ('trivia_fact', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='filmedby',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.movie'),
        ),
        migrations.AddField(
            model_name='filmedby',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.studio'),
        ),
        migrations.CreateModel(
            name='EasyTrivia',
            fields=[
                ('trivia_id', models.AutoField(primary_key=True, serialize=False)),
                ('trivia_fact', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.movie')),
            ],
            options={
                'unique_together': {('movie', 'actor')},
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='trivia_game.Casts', to='trivia_game.Movie'),
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.movie')),
            ],
            options={
                'unique_together': {('movie', 'company_name')},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.movie')),
            ],
            options={
                'unique_together': {('movie', 'type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='filmedby',
            unique_together={('movie', 'studio')},
        ),
    ]
