# Generated by Django 5.1.3 on 2024-11-25 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trivia_game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EasyTrivia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trivia_fact", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="easy_trivia",
                        to="trivia_game.movie",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Easy Trivia",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HardTrivia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trivia_fact", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_trivia",
                        to="trivia_game.movie",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hard Trivia",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediumTrivia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trivia_fact", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medium_trivia",
                        to="trivia_game.movie",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medium Trivia",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("founding_year", models.IntegerField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=200)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_companies",
                        to="trivia_game.movie",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Production Companies",
            },
        ),
        migrations.DeleteModel(
            name="Trivia",
        ),
    ]
